version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - "8081:8081"  #local-machine-port:docker-container-port
    depends_on:
      - mongo_db

  mongo_db:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"